# Generated by Django 3.2.3 on 2023-05-12 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(default='XXXX', help_text='Введите код подтверждения,который был отправлен на ваш email', max_length=255, null=True, verbose_name='Код подтверждения'),
        ),
    ]
